[package]
name = "hallpass-cli"
version.workspace = true
edition.workspace = true
license.workspace = true
description = "Hallpass application firewall CLI"

[dependencies]
hallpass-types = { path = "../hallpass-types" }
serde = { workspace = true }
serde_json = { workspace = true }
tokio = { workspace = true, features = [
    "rt",
    "net",
    "macros",
    "io-util",
    "io-std",
    "signal",
    "sync",
    "time",
] }

[lints]
workspace = true
