[package]
name = "hallpass-ui"
version.workspace = true
edition.workspace = true
license.workspace = true
description = "Hallpass application firewall desktop UI"

[dependencies]
hallpass-types = { path = "../hallpass-types" }
eframe = "0.35"
chrono = { version = "0.4", default-features = false, features = ["clock"] }
tokio = { workspace = true, features = [
    "rt",
    "net",
    "sync",
    "time",
    "io-util",
    "macros",
] }
tracing = { workspace = true }
tracing-subscriber = { version = "0.3", features = ["env-filter"] }

[lints]
workspace = true
