[package]
name = "sentinel-cli"
version.workspace = true
edition.workspace = true
license.workspace = true
description = "Sentinel application firewall CLI"

[dependencies]
sentinel-types = { path = "../sentinel-types" }
tokio = { workspace = true, features = [
    "rt",
    "net",
    "macros",
    "io-util",
    "io-std",
    "signal",
    "sync",
    "time",
] }

[lints]
workspace = true
